// Expenses by Category
export const GET_EXPENSES_BY_CATEGORY_REQUEST = "GET_EXPENSES_BY_CATEGORY_REQUEST";
export const GET_EXPENSES_BY_CATEGORY_SUCCESS = "GET_EXPENSES_BY_CATEGORY_SUCCESS";
export const GET_EXPENSES_BY_CATEGORY_FAILURE = "GET_EXPENSES_BY_CATEGORY_FAILURE";

// Income by Category
export const GET_INCOME_BY_CATEGORY_REQUEST = "GET_INCOME_BY_CATEGORY_REQUEST";
export const GET_INCOME_BY_CATEGORY_SUCCESS = "GET_INCOME_BY_CATEGORY_SUCCESS";
export const GET_INCOME_BY_CATEGORY_FAILURE = "GET_INCOME_BY_CATEGORY_FAILURE";

// Expenses by Date
export const GET_EXPENSES_BY_DATE_REQUEST = "GET_EXPENSES_BY_DATE_REQUEST";
export const GET_EXPENSES_BY_DATE_SUCCESS = "GET_EXPENSES_BY_DATE_SUCCESS";
export const GET_EXPENSES_BY_DATE_FAILURE = "GET_EXPENSES_BY_DATE_FAILURE";

// Income by Date
export const GET_INCOME_BY_DATE_REQUEST = "GET_INCOME_BY_DATE_REQUEST";
export const GET_INCOME_BY_DATE_SUCCESS = "GET_INCOME_BY_DATE_SUCCESS";
export const GET_INCOME_BY_DATE_FAILURE = "GET_INCOME_BY_DATE_FAILURE";
